"""add_notes_and_status_to_employees

Revision ID: 044325bdc8ea
Revises: d2e3f4a5b6c7
Create Date: 2026-05-28 20:03:43.630940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044325bdc8ea'
down_revision: Union[str, Sequence[str], None] = 'd2e3f4a5b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('status', sa.String(), nullable=False, server_default='active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'status')
    op.drop_column('employees', 'notes')
    # ### end Alembic commands ###
